### ISSUE TITLE
Issues when defining 'valid_recon_range' on mesolf_set_params.m

### ISSUE THREAD

**Issue by JAMoreno-Larios** [vazirilab/MesoLF#1]
Hello,

I am currently implementing a Light Field Microscope at Sjulson and Batista-Brito labs in Albert Einstein College of Medicine. I appreciate your efforts in providing a pipeline to facilitate in-vivo brain analysis.

I found a couple of issues on file 'mesolf_set_params.m' when evaluating 'valid_recon_range' field:

` {'valid_recon_range',           @(x) isinteger(x) && @(x) mod(x,2) == 1,      51};`

The first one is that MATLAB, by default, declares all numeric values as doubles, thus when evaluating `isinteger(x)` we will get a false value unless we explicitly declare the desired reconstruction value as an integer using any of MATLAB integer class constructors, however, if I do that there will be indexing problems when removing the top and bottom slabs on the reconstruction module given how MATLAB does division with integer - e. g. int32(12) / 2 = 6 instead of 5.5. I replaced `isinteger(x)` with `isPositiveIntegerValuedNumeric(x)` and it seems to work as intended.

The second issue is that when I evaluate `@(x) isinteger(x) && @(x) mod(x,2) == 1` I get an 'is:Conversion to logical form function_handle is not possible.' error. The way I fixed this is to change from

` {'valid_recon_range',           @(x) isinteger(x) && @(x) mod(x,2) == 1,      51};` 
to
`{'valid_recon_range',           @(x) isinteger(x) && mod(x,2) == 1,      51};`

Thank you for your attention.

**Comment by nobias** [comment]
Hi! Thank you very much for this detailed bug report and the suggested solutions, and apologies for the mistake. I just pushed a commit that implements your suggestions in slightly altered form. Please do let me know if you run into any further issues!
